update git file

diff --git a/.github/workflows/update-images.yaml b/.github/workflows/update-images.yaml
--- a/.github/workflows/update-images.yaml
+++ b/.github/workflows/update-images.yaml
@@ -52,27 +52,42 @@ jobs:
         run: |
           set -euo pipefail
 
-          IMAGE_TAG="${{inputs.SERVICES}}:${{ inputs.IMAGE_TAG }}"
+          IMAGE_TAG="${{ inputs.IMAGE_TAG }}"
           STARTING_PATH="${{ inputs.STARTING_PATH }}"
           IDENTIFIER_COMMENT="${{ inputs.IDENTIFIER_COMMENT }}"
+          SERVICES="${{ inputs.SERVICES }}"
 
           echo "IMAGE_TAG=$IMAGE_TAG"
           echo "STARTING_PATH=$STARTING_PATH"
           echo "IDENTIFIER_COMMENT=$IDENTIFIER_COMMENT"
+          echo "SERVICES=$SERVICES"
+
+          SERVICE_MARKER="#$(echo "$SERVICES" | tr '[:lower:]' '[:upper:]')"
 
           find "$STARTING_PATH" -type f \( -name "*.yaml" -o -name "*.yml" \) \
             -exec grep -l "$IDENTIFIER_COMMENT" {} \; | while read -r file; do
 
               echo "Processing $file"
 
+              if ! grep -q "$SERVICE_MARKER" "$file"; then
+                echo "Skipping (service marker not found): $file"
+                continue
+              fi
+
+              echo "Updating service file: $file"
+
               # Pattern 1:
               # image: nginx:1.0.0 # DEV_IMAGE_TAG (used for Kubernetes manifest)
-                  sed -i "s|\(\s*image:\s*\).*${IDENTIFIER_COMMENT}|\1${IMAGE_TAG} ${IDENTIFIER_COMMENT}|g" "$file"
-             
+                  sed -E -i \
+                  "s|(image:\s*[^:]+:)[^[:space:]]+(\s*${IDENTIFIER_COMMENT}.*)|\1${IMAGE_TAG}\2|g" \
+                  "$file"
+                              
               
               # Pattern 2:
               # tag: nginx:1.0.0 # DEV_IMAGE_TAG (used for HELM manifest )
-                sed -i "s|\(\s*tag:\s*\).*${IDENTIFIER_COMMENT}|\1${IMAGE_TAG} ${IDENTIFIER_COMMENT}|g" "$file"
+                 sed -E -i \
+                "s|(tag:\s*)[^[:space:]]+(\s*${IDENTIFIER_COMMENT}.*)|\1${IMAGE_TAG}\2|g" \
+                "$file"
 
               echo "$file updated"
           done
